### ISSUE TITLE
[Bug]: Unable to create first user on brand new local Docker installation

### ISSUE THREAD

**Issue by dsaltares** [OpenSignLabs/OpenSign#1158]
### Issue Description

I am not presented with a first-time setup to create an admin user when I first open the app on a local Docker installation. This is similar to https://github.com/OpenSignLabs/OpenSign/issues/973, but I am on `2.2.0` (have also tried `main`).

### Expected Behavior

Judging from comments (https://github.com/OpenSignLabs/OpenSign/issues/1080#issue-2476655525). I am meant to see a user registration screen the first time I use the app.

### Current Behavior

I am presented with a login screen that reads `Welcome back!`, but there are not registered users.

### Steps to reproduce

Follow the instructions to self-host from https://docs.opensignlabs.com/docs/self-host/docker/run-locally

``` 
export HOST_URL=https://opensign.yourdomain.com && curl --remote-name-all https://raw.githubusercontent.com/OpenSignLabs/OpenSign/main/docker-compose.yml https://raw.githubusercontent.com/OpenSignLabs/OpenSign/main/Caddyfile https://raw.githubusercontent.com/OpenSignLabs/OpenSign/main/.env.local_dev && mv .env.local_dev .env.prod && docker compose up --force-recreate`
```

I also tried tagging a specific version (2.2.0):
```
export HOST_URL=https://opensign.saltares.dev && curl --remote-name-all https://raw.githubusercontent.com/OpenSignLabs/OpenSign/v2.2.0/docker-compose.yml https://raw.githubusercontent.com/OpenSignLabs/OpenSign/v2.2.0/Caddyfile https://raw.githubusercontent.com/OpenSignLabs/OpenSign/v2.2.0/.env.local_dev && mv .env.local_dev .env.prod && docker compose up --force-recreate
```

### Screenshots of the issue(optional)

<img width="1508" alt="image" src="https://github.com/user-attachments/assets/cf4ad89f-b61f-4a65-8654-6fadca04564e">

### Operating System [e.g. MacOS Sonoma 14.1, Windows 11]

MacOS Ventura 13.6.7

### What browsers are you seeing the problem on?

Chrome

### What version of OpenSign™ are you seeing this issue on? [e.g. 1.0.6]

2.2.0

### What environment are you seeing the problem on?

Hosted (app.yourdomain.com)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

**Comment by rick-hmc** [comment]
Same for me - I have been through every document on the website and it seems like the initialisation is something that is normal process but not happening in the latest build.

**Comment by useahawk** [comment]
I have the same Problem and it seems to be a duplicate of #1115 .
Couldn't find anything in the docs ether.

**Comment by dsaltares** [comment]
@useahawk that's right, my bad for not finding that one although it doesn't say how it was fixed.

**Comment by useahawk** [comment]
I got it solved for my env.
Testing localhost:3000 showed welcome page
Testing localhost:3001 showed not available
Testing localhost:443 showed register page

Looing at the Caddyfile it makes sense, so i tweaked my ports in live env as needed (cant use any of the 3000, 3001, 8080, 80 or 443 ports) and fixed my own reverse proxy with the rules from the Caddyfile.

Finally it's working!

**Comment by dsaltares** [comment]
With a fresh installation of opensign this is what I get.

`localhost:3000`
<img width="1509" alt="image" src="https://github.com/user-attachments/assets/490af514-c40c-4745-b448-0933d1c51ab2">

`localhost:3001`
<img width="782" alt="image" src="https://github.com/user-attachments/assets/4c448d22-c2a1-46f0-ba8a-32e72caef184">

`https://localhost:443`
<img width="747" alt="image" src="https://github.com/user-attachments/assets/31f7a0f7-48f0-4608-be6a-49211a3ce25e">

What modifications did you make exactly?

**Comment by prafull-opensignlabs** [comment]
[docs](https://docs.opensignlabs.com/docs/self-host/docker/run-locally)
hey @dsaltares , please checkout this updated [documentation](https://docs.opensignlabs.com/docs/self-host/docker/run-locally) and let us know if you still encounter any issues.

**Comment by davisk4rpi** [comment]
> hey @dsaltares , please checkout this updated [documentation](https://docs.opensignlabs.com/docs/self-host/docker/run-locally) and let us know if you still encounter any issues.

I just came across this issue setting up a fresh project. I followed the linked docs, but `https://localhost:3001` still showed the "welcome back" page instead of allowing me to register.

Turns out, theres an easy mistake in the .env files for `MOGODB_URI`
```
https://raw.githubusercontent.com/OpenSignLabs/OpenSign/main/.env.local_dev
https://raw.githubusercontent.com/OpenSignLabs/OpenSign/docker_beta/.env.local_dev
```

The value provided by the copied envs is `mongodb://mongo-container:27017/OpenSignDB`, but it should be `mongodb://mongo:27017/OpenSignDB`

Docker uses the service name for the in-network host, not the container name.

**Comment by andrew-opensignlabs** [comment]
> > hey @dsaltares , please checkout this updated [documentation](https://docs.opensignlabs.com/docs/self-host/docker/run-locally) and let us know if you still encounter any issues.
> 
> 
> 
> I just came across this issue setting up a fresh project. I followed the linked docs, but `https://localhost:3001` still showed the "welcome back" page instead of allowing me to register.
> 
> 
> 
> Turns out, theres an easy mistake in the .env files for `MOGODB_URI`
> 
> ```
> 
> https://raw.githubusercontent.com/OpenSignLabs/OpenSign/main/.env.local_dev
> 
> https://raw.githubusercontent.com/OpenSignLabs/OpenSign/docker_beta/.env.local_dev
> 
> ```
> 
> 
> 
> The value provided by the copied envs is `mongodb://mongo-container:27017/OpenSignDB`, but it should be `mongodb://mongo:27017/OpenSignDB`
> 
> 
> 
> Docker uses the service name for the in-network host, not the container name.
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

What OS are you using? For most of us container name works instead of service name.

**Comment by davisk4rpi** [comment]
macOS

As far as I am aware service name works on all systems on the latest docker

**Comment by davisk4rpi** [comment]
@andrew-opensignlabs 
If using the service name is problematic, maybe network alias's would work to straighten this out? 

https://docs.docker.com/reference/compose-file/services/#aliases

**Comment by reddexx** [comment]
The problem also concerns me, I wanted to try opensign, but unfortunately I can't because I get directly to the login form

My Compose:
`services:
  server:
    image: opensign/opensignserver:main  # Überprüfe die Nutzung stabiler Tags
    container_name: OpenSignServer-container
    ports:
      - "8991:8080"
    depends_on:
      - mongo
    env_file: .env.prod  # Stelle sicher, dass diese Datei existiert
    environment:
      - NODE_ENV=production
      - SERVER_URL=${HOST_URL-https://localhost:3001/app}  # Standard war hier direkt
    networks:
      - opensign-network

  mongo:
    image: mongo:latest
    container_name: mongo-container
    volumes:
      - /Container/opensign/db:/data/db
    ports:
      - "27018:27017"
    networks:
      - opensign-network

  client:
    image: opensign/opensign:main  # Überprüfe auch hier die Nutzung stabiler Tags
    container_name: OpenSign-container
    depends_on:
      - server
    env_file: .env.prod  # Überprüfe auch diese Datei
    ports:
      - "3000:3001"
    networks:
      - opensign-network


networks:
  opensign-network:
    driver: bridge`

**Comment by santosh2494** [comment]
Same issue with my installation as well.

**Comment by D3Dgroupe** [comment]
Hello, I have the same problem, do you know which container it could come from ? This is a new installation.

**Comment by bobvandevijver** [comment]
For me this was caused by not using `opensign` as the APP_ID.

**Comment by bobvandevijver** [comment]
> thank you, that was it! But why?

See #1256, that would be my guess

**Comment by D3Dgroupe** [comment]
Hello, after a lot of modification of the docker-compose file and the environment file I managed to deploy the server on Portainer and it is accessible from the internet.
I think my problem came from the fact that I had forgotten in the docker-compose the lines "volumes":

```
  server:
    image: opensign/opensignserver:main
    container_name: OpenSignServer-container
    **volumes:
      - opensign-files:/usr/src/app/files**

```
and its declaration in the volumes

**Comment by OvoiDs** [comment]
Hum, this seems to be a very common error with multiple sources.

I am facing this issue too and I guess it is related to network configuration but I cannot seem to find what I did wrong...  
I've tried quite a lot of stuff on premise, but keptfacing the error message that state I already have an admin configured. I decided to stop trying on premise and try using Digital Ocean as the deployment was supposedly easy. 

Here's the URL from Digital Ocean : https://opensign-nxppm.ondigitalocean.app/addadmin

Here's the trace from firefox's console:
err in getlogo  Error: XMLHttpRequest failed: "SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data"
    c ParseError.js:27
    handleError RESTController.js:300
    promise callback*request RESTController.js:284
    run Cloud.js:114
    run Cloud.js:60
    jy Utils.js:2062
    z AddAdmin.js:51
    h AddAdmin.js:45

The request payload: {"domain":"opensign-nxppm.ondigitalocean.app","_ApplicationId":"opensign","_ClientVersion":"js5.3.0","_InstallationId":"79dafa96-57c3-4e3d-baa2-dc29a300cef1"}

The response: <!doctype html><html lang="en" data-theme="opensigncss"><head><meta charset="utf-8"/><link rel="icon" href="/favicon.ico"/><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"/><meta name="theme-color" content="#000000"/><meta name="description" content="The fastest way to sign PDFs & request signatures from others"/><link rel="manifest" href="/manifest.json"/><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"/><link rel="stylesheet" href="https://cdn.opensignlabs.com/fonts.css"/><title>...Loading</title><script defer="defer" src="/static/js/main.d3f0d017.js"></script><link href="/static/css/main.38a04d1d.css" rel="stylesheet"></head><body><div id="root" style="touch-action:pan-x pan-y"></div></body></html>

It seems like this should be offloaded to the opensign server @ 8080 (because when I request that directly to the opensign server, it states, on my on premise server : 
sysadmin@opensignqualif:~$ curl -X POST http://localhost:8080/app/functions/getlogobydomain -H "X-Parse-Application-Id: opensign"
{"result":{"logo":"","appname":"OpenSign™","user":"not_exist"}}

Both DigitalOcean and on premise install are failing in the same way (same error message).

There also seems to be a second error which prevents me from using chrome based browsers (it fails loading the page). 

![Image](https://github.com/user-attachments/assets/eca59013-73ce-4db4-ace9-ca129e46efbb)

I suspect the on premise install fails for another reason (not web accessible ==> no let's encrypt ==> no working https out of the box ==> may annoy the app, but not sure). But have to say that since I do not know react and all, I'm having a hard time to debug.

**Comment by nmbgeek** [comment]
> [@andrew-opensignlabs](https://github.com/andrew-opensignlabs) please allow setup on the PUBLIC_URL, with headless servers we can't access localhost, much less localhost:3001 which opensign needs

Did you ever find a resolution to this?

**Comment by ColdAssass1n** [comment]
This is for those of you that have a reverse proxy already like Nginx Proxy Manager or Pangolin that handles the SSL Certs. I have 20+ years in IT, and 10+ years in networking, and 5+ years in reverse proxy and customer of mine requested a pdf signer. 

I have pangolin running that does my letsencrypt stuff for all my sites, I have a pangolin site connector installed on my docker host that runs opensign docker. I create a public resource called opensign and picked a subdomain, in this example abc.com, target I selected the docker host "site" in the dropdown, and pointed it to http://127.0.0.1:3001 (so in otherwords look at docker host yourself but port 3001 and tunnel me that)

The problem comes down to Caddy wanting to create its own cert for this. That's getting in your way. In the caddy file, we have set "{$HOST_URL}", but we are setting that to an https address. Because of this, Caddy will attempt to do challenges against the host like DNS to try an get a cert for you... You don't want that, trust me. So as usual,

On the docker side:
```
export HOST_URL=https://opensign.abc.com

# Download fresh files
curl --remote-name-all \
  https://raw.githubusercontent.com/OpenSignLabs/OpenSign/main/docker-compose.yml \
  https://raw.githubusercontent.com/OpenSignLabs/OpenSign/main/Caddyfile \
  https://raw.githubusercontent.com/OpenSignLabs/OpenSign/main/.env.local_dev

mv .env.local_dev .env.prod
```
Update .env.prod: 
```
Find: 
SERVER_URL=http://127.0.0.1:8080/app
Replace WIth:
SERVER_URL=http://server:8080/app

```
I then updated my Caddy File: Replace the top {$HOST_URL} with :3001 (most important STEP!!!!)
Mine:
```
:3001 {
    reverse_proxy client:3000
    handle_path /api/* {
        reverse_proxy server:8080
            rewrite * {uri}
    }
}
```

# Start it
```
docker compose up -d
docker compose logs caddy
```
The logs for caddy should look much cleaner and things should work now when you go to the public URL. If you aren't redirected to /addadmin, give it at least 30 seconds and do a hard refresh.

Also for troubleshooting, you can always set the HOST_URL to localhost:3001

```
cd ~/opensign

# Stop current containers
docker compose down

# Set HOST_URL to the port you'll tunnel
export HOST_URL=https://localhost:3001

# Download fresh files
curl --remote-name-all \
  https://raw.githubusercontent.com/OpenSignLabs/OpenSign/main/docker-compose.yml \
  https://raw.githubusercontent.com/OpenSignLabs/OpenSign/main/Caddyfile \
  https://raw.githubusercontent.com/OpenSignLabs/OpenSign/main/.env.local_dev

mv .env.local_dev .env.prod

# Start it
docker compose up -d
```
I can't remember if you have to set PUBLIC_URL=https://localhost:3001 in the .env.prod

Then Tunnel into the docker host (if it isn't on your machine)
`ssh -L 3001:localhost:3001 username@docker.host.ip.or.fqdn`
Then you can use a browser on your local (not docker host) machine https://localhost:3001 (accept the security warning) to access the site... This was how I was first able to get to the /Addadmin interface the first time around before the caddy fix above on my headless server.

Hope this helps someone else. Cheers

**Comment by Joey4tunato** [comment]
hey all! is there a plan on this being fixed?

**Comment by cosmic-zip** [comment]
> hey all! is there a plan on this being fixed?

Did you try to unset the variable HOST_URL? This is causing the hole problem for me.
